### ISSUE TITLE
Подумать над мл-компонентом

### ISSUE THREAD

**Issue by vladislavsheludchenkov** [OrangeFlag/AliSOS#2]
Запилить десижн-три или что угодно ещё. Главное - по анамнезу получать рекомендации по врачу.

**Comment by HiddenTreasure525** [comment]
Так, я спросил у врачей, можно ли у них достать данные, чтобы был датасет. Ситуация такая, у них на заходе при звонке сразу кодируется ведущее заболевание, поэтому такие прям сырые тексты мы не получим никак, кроме личного выдумывания, все остальное хранится в отделе статистики и видимо в бумажном виде с того, что привозит бригада

**Comment by vladislavsheludchenkov** [comment]
Таска выполнена, завтра будем презентовать.
