### ISSUE TITLE
Небольшие правки по AliSOS Mock Clinic Server

### ISSUE THREAD

**Issue by vladislavsheludchenkov** [OrangeFlag/AliSOS#25]
1. Изменить эндпоинт POST /patient на POST /api/patient
2. Настроить роутинг так, что если роут начинается с api, то express ищет его у себя, а иначе возвращает UI
3. Убрать postinstall у patients-list
4. Добавить ng-build в postinstall корневого проекта (того, что на экспрессе)
5. Убрать из параметров ng-build параметр base-href
6. Очень аккуратно переименовать patients-list в clinic-ui
7. Написать нормальные тесты или удалить автосгенерированные тесты
8. Убрать лишние devDependencies из package.json (почти все)
9. Заменить абсолютные урлы на обращение к апи на относительные, так как фронт и бэк будут деплоиться на одну и ту же машину

**Comment by karasikrus** [comment]
> Убрать из параметров ng-build параметр base-href

Вот это вот не знаю, как и зачем делать
