### ISSUE TITLE
Перенести ин-мемори хранилище в постгрес

### ISSUE THREAD

**Issue by vladislavsheludchenkov** [OrangeFlag/AliSOS#3]
У нас сейчас собранная информация для пользователя хранится тупо в мапе. Нужно вместо этого использовать РБД - завести табличку с пользователями, у которых будут примерно такие поля: айдишник, анамнез, адрес, телефон, дата обновления анамнеза, дата обновления адреса, дата обновления телефона. Если анамнез и телефон ещё не заполнены, то и дата обновления должна быть null.

**Comment by vladislavsheludchenkov** [comment]
Просьба также в рамках этой задачи пофиксить дефект:
Сейчас после завершения диалога сбрасываются все данные по пользователю. Нужно сбрасывать только анамнез.

**Comment by OrangeFlag** [comment]
@OrangeMemes дефект, да? Как же на тебя тестирка зловредно влияет

**Comment by DanonOfficial** [comment]
@OrangeFlag, это же стандартное именование, а Влад на ее пары вообще не ходит :/

**Comment by OrangeFlag** [comment]
> @OrangeFlag, это же стандартное именование, а Влад на ее пары вообще не ходит :/

Тогда простите
