### ISSUE TITLE
Уточнять у пользователя актуальность данных

### ISSUE THREAD

**Issue by vladislavsheludchenkov** [OrangeFlag/AliSOS#4]
Если анамнез, адрес или телефон обновлялись очень давно (раньше, чем час назад), то нужно спрашивать, всё ли в силе.

Нужно:
1. Завести в БД в табличке с пользователями флаги waiting_for_address_confirmation и waiting_for_phone_confirmation типа булеан с дефолтным значением false
2. Сделать новую ветку диалога, по приоритету выше конца диалога, но ниже всех остальных. Условие для этой ветки - время обновления адреса и/или телефона не null и старше, чем час назад.
При попадании в эту ветку ставим в true флажок, соответствующий тому, что у пользователя старое (или оба флажка, если и то, и другое) и отправляем ответ в соответствии с таблицей

| адрес  | телефон | сообщение                                     |
|--------|---------|-----------------------------------------------|
| старый | новый   | Вы сейчас здесь? %address%                    |
| новый  | старый  | Сюда можно будет позвонить? %phone%           |
| старый | старый  | Всё верно? Адрес: %address%, телефон: %phone% |

3. Все ветки, кроме ветки, разработанной в пункте 2, сбрасывают оба флажка в false
4. Если сообщение пользователя содержит токен "да" (регистронезависимо), то переставляем дату обновления телефона и/или адреса (того, чей флаг поднят) на текущую
5. Если сообщение пользователя начинается с "нет" (регистронезависимо), то сбрасываем телефон и/или адрес (того, чей флаг поднят) и дату его обновления в null
6. Пункты 4-5 должны выполняться перед всем остальным процессингом сообщения (то есть до того, как начнут распознаваться адрес/телефон)

**Comment by HiddenTreasure525** [comment]
Я не понял в чем суть, можно объяснить?

**Comment by vladislavsheludchenkov** [comment]
суть в том что я случайно опубликовал ишую без описания

**Comment by vladislavsheludchenkov** [comment]
дописал

**Comment by vladislavsheludchenkov** [comment]
Заблокировано задачей #3
